before_commands:
    - "composer install --prefer-source"
filter:
    paths: [src/*]
    excluded_paths: [vendor/*, tests/*, examples/*]
tools:
    php_mess_detector: true
    php_analyzer: true
    php_code_sniffer:
        config:
            standard: PSR2
    php_code_coverage:
        test_command: phpunit
        config_path: ~
    php_cpd:
        excluded_dirs:
            - tests
            - vendor
    php_loc: true