probes:
  Google.com_HTTP:
    type: Http
    options:
      url: http://www.google.com
      expectedHttpCode: 302
      timeout: 5
  Google.fr_HTTPS:
    type: Http
    options:
      url: https://www.google.fr
      expectedHttpCode: 200
      timeout: 5
      contains: <title>Google</title>
  Google_DNS:
    type: Tcp
    adapter: Netcat
    options:
      host: 8.8.8.8
      port: 53
  MySQL_Local:
    type: Database
    options:
      host: localhost
      user: root
      password:
      database: mysql
